# Generated by Django 4.0.6 on 2022-09-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_address',
            field=models.BooleanField(default=False),
        ),
    ]
