# Generated by Django 4.0.6 on 2022-08-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
