# Generated by Django 4.0.6 on 2022-09-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_useraddress_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
