# Generated by Django 4.0.6 on 2022-08-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='pro_qty_price',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
