# Generated by Django 4.0.6 on 2022-08-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'size',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_gen', models.CharField(choices=[('all', 'all'), ('men', 'men'), ('women', 'women'), ('kids', 'kids')], default='all', max_length=30, null=True)),
                ('product_name', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('discription', models.TextField(blank=True, max_length=500)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
                ('stock', models.CharField(max_length=50, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('permition', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default='select any one', on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('size_chart', models.ForeignKey(blank=True, default='select any one', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.size_chart')),
            ],
        ),
    ]
