# Generated by Django 4.0.6 on 2023-04-27 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_size_chart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(400), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
