# Generated by Django 4.0.6 on 2023-05-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_images_image_name_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_chart',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
