# Generated by Django 4.0.6 on 2023-05-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_size_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='media/image'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
