# Generated by Django 4.0.6 on 2023-05-06 06:10

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, unique=True, validators=[category.models.Category.validate_catogory_name]),
        ),
    ]
