# Generated by Django 4.0.6 on 2022-09-16 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('checkout', '0003_alter_useraddress_phone_number'),
        ('order', '0003_payment_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOnDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_status', models.CharField(choices=[('shipping', 'shipping'), ('pending', 'pending'), ('delivered', 'delivered'), ('cancel', 'cancel')], max_length=50, null=True)),
                ('payment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.useraddress')),
            ],
        ),
    ]
